### ISSUE TITLE
Before a Receiver creates a stream, there is no way for it to discover which events a Transmitter supports for it

### ISSUE THREAD

**Issue by tulshi** [openid/sharedsignals#45]
Section 7.1.1.2 specifies that before a stream is created the response sent by the Transmitter is empty. It should be the list of events supported by the Transmitter for that Receiver.

**Comment by FragLegs** [comment]
Good catch! I wonder if we should move `events_supported` to the Transmitter Configuration instead of the Stream Configuration. It's more a property of the transmitter than the stream - i.e. it won't change from stream to stream. And it would get us around having to return a somewhat kludgy Stream Configuration response when no streams have been created.

**Comment by tulshi** [comment]
It could be receiver specific though. A Transmitter may want to support one set of events for one Receiver, and another set of events for another Receiver.

**Comment by tulshi** [comment]
See notes https://hackmd.io/@oidf-wg-sse/wg-meeting-20230606, only change will be to the description of "events requested" and "events delivered" in the stream configuration description. This functionality (of discovering events supported before creating a stream) need not be added to the spec.
