### ISSUE TITLE
Breaking change introduced in the latest draft - `endpoint_url` is renamed to `url`

### ISSUE THREAD

**Issue by appsdesh** [openid/sharedsignals#79]
Hello, 

I am noticing a breaking change introduced in [this](https://github.com/openid/sharedsignals/commit/ae0cf793477bff3953001b1f4ef04da78b9325e1) commit related to the `delivery` object, that is renaming `endpoint_url` from the approved spec [11.2.1.1](https://openid.net/specs/openid-sse-framework-1_0-ID1.html#rfc.section.11.2.1.1) to `url`. We will have to revert this before approving the draft

**Comment by tulshi** [comment]
I'm trying to understand the impact of this change, since it is only related to the metadata and it is used in the examples in the previous implementer's draft (although the section defined it as "endpoint_url"). Could you please comment on whether this is impactful to existing implementations or hard to update?
